sudo: required

language: cpp

compiler: g++

branches:
  only:
    - develop

cache:
  apt: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:wsnipex/kodi-git -y
  - sudo apt-get update
  - sudo apt-get install -qq libgoogle-glog0v5 g++-5 gcc-5 libglm-dev libassimp-dev rapidjson

before_script:
  - export CXX="g++-5"
  - export CC="gcc-5"

script:
  - mkdir build && cd build
  - cmake ..
  - make