sudo: required
dist: trusty

language: cpp

compiler: g++

branches:
  only:
    - develop

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-5
      - g++-5
      - libassimp-dev
      - libgoogle-glog-dev
      - libglm-dev
      - rapidjson-dev

cache:
  apt: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -qq libgoogle-glog-dev g++-5

before_script:
  - export CXX="g++-5"
  - export CC="gcc-5"

script:
  - mkdir build && cd build
  - cmake ..
  - make