sudo: required
dist: trusty

language: cpp

compiler: g++

branches:
  only:
    - develop

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - gcc-5
      - libassimp-dev
      - libgoogle-glog-dev
      - libglm-dev
      - rapidjson-dev

cache:
  apt: true


before_script:
  - export CXX="g++-4.8"

script:
  - mkdir build && cd build
  - cmake ..
  - make